window.INITIAL_DATA = {
  "title": "카드별 지출 현황 및 가계부 대시보드",
  "subtitle": "뱅크샐러드 데이터 기반 (2026-09-01 ~ 2026-09-10)",
  "period": "2026-09-01 ~ 2026-09-10",
  "physicalCards": [
    "신한은행 The More",
    "KT Plus 우리카드",
    "MG+ S 하나카드",
    "KB국민 톡톡 my point카드",
    "다드림 LOVE",
    "아시아나 KB국민플래티늄카드",
    "기타 카드"
  ],
  "payAndAccounts": [
    "[간편결제] 네이버페이",
    "[간편결제] 네이버페이(포인트)",
    "[간편결제] 카카오페이",
    "[간편결제] 페이코",
    "[간편결제] 토스",
    "계좌/현금"
  ],
  "allCards": [
    "신한은행 The More",
    "KT Plus 우리카드",
    "MG+ S 하나카드",
    "KB국민 톡톡 my point카드",
    "다드림 LOVE",
    "아시아나 KB국민플래티늄카드",
    "기타 카드",
    "[간편결제] 네이버페이",
    "[간편결제] 네이버페이(포인트)",
    "[간편결제] 카카오페이",
    "[간편결제] 페이코",
    "[간편결제] 토스",
    "계좌/현금"
  ],
  "records": [
    {
      "id": 1,
      "origId": 170,
      "date": "2026-09-01",
      "time": "08:59:57",
      "month": "9월",
      "category": "의료/건강",
      "subCategory": "보조식품",
      "merchant": "더리틀스",
      "amount": 51840,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 51840,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 2,
      "origId": 171,
      "date": "2026-09-01",
      "time": "09:09:03",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 62050,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 62050,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 3,
      "origId": 172,
      "date": "2026-09-01",
      "time": "09:48:17",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "간편결제_에스에스지페이먼츠",
      "amount": 2900,
      "origPay": "MG+ S 하나카드",
      "actualCard": "MG+ S 하나카드",
      "installment": "일시불",
      "billingAmount": 2900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 4,
      "origId": 173,
      "date": "2026-09-01",
      "time": "11:00:38",
      "month": "9월",
      "category": "금융",
      "subCategory": "은행",
      "merchant": "송금 내역",
      "amount": 11400,
      "origPay": "카카오페이 머니",
      "actualCard": "계좌/현금",
      "installment": "일시불",
      "billingAmount": 11400,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 5,
      "origId": 174,
      "date": "2026-09-01",
      "time": "11:18:23",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡(주)",
      "amount": 7900,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 7900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 6,
      "origId": 175,
      "date": "2026-09-01",
      "time": "12:26:28",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 25600,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 25600,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 7,
      "origId": 176,
      "date": "2026-09-01",
      "time": "15:02:15",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "결제/충전",
      "merchant": "헥토_구인증",
      "amount": 5000,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 8,
      "origId": 177,
      "date": "2026-09-02",
      "time": "01:15:00",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡",
      "amount": 15960,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 15960,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 9,
      "origId": 178,
      "date": "2026-09-02",
      "time": "01:39:26",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 16700,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 16700,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 10,
      "origId": 179,
      "date": "2026-09-02",
      "time": "01:43:08",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 19600,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 19600,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 11,
      "origId": 180,
      "date": "2026-09-02",
      "time": "01:45:04",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡(주)",
      "amount": 9630,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 9630,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 12,
      "origId": 182,
      "date": "2026-09-02",
      "time": "11:05:24",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡(주)",
      "amount": 5900,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 13,
      "origId": 183,
      "date": "2026-09-02",
      "time": "11:25:53",
      "month": "9월",
      "category": "카페/간식",
      "subCategory": "커피/음료",
      "merchant": "(주) 카페크리스피",
      "amount": 9400,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 9400,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 14,
      "origId": 184,
      "date": "2026-09-02",
      "time": "11:50:36",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 12300,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 12300,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 15,
      "origId": 185,
      "date": "2026-09-02",
      "time": "13:29:18",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "인터넷상거래",
      "amount": 120666,
      "origPay": "다드림 LOVE",
      "actualCard": "다드림 LOVE",
      "installment": "일시불",
      "billingAmount": 120666,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 16,
      "origId": 186,
      "date": "2026-09-02",
      "time": "15:57:26",
      "month": "9월",
      "category": "생활",
      "subCategory": "목욕",
      "merchant": "테리파머",
      "amount": 29900,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 29900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 17,
      "origId": 187,
      "date": "2026-09-02",
      "time": "16:40:38",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": -12300,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": -12300,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 18,
      "origId": 188,
      "date": "2026-09-02",
      "time": "16:43:08",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 13300,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 13300,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 19,
      "origId": 189,
      "date": "2026-09-02",
      "time": "19:19:00",
      "month": "9월",
      "category": "생활",
      "subCategory": "편의점",
      "merchant": "CU(페럼타워점)",
      "amount": 10600,
      "origPay": "페이코 간편결제",
      "actualCard": "[간편결제] 페이코",
      "installment": "일시불",
      "billingAmount": 10600,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 20,
      "origId": 191,
      "date": "2026-09-03",
      "time": "17:04:32",
      "month": "9월",
      "category": "식비",
      "subCategory": "배달",
      "merchant": "요기요",
      "amount": 66000,
      "origPay": "페이코 간편결제",
      "actualCard": "[간편결제] 페이코",
      "installment": "일시불",
      "billingAmount": 66000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 21,
      "origId": 192,
      "date": "2026-09-03",
      "time": "17:04:32",
      "month": "9월",
      "category": "식비",
      "subCategory": "배달",
      "merchant": "요기요",
      "amount": 4500,
      "origPay": "페이코 간편결제",
      "actualCard": "[간편결제] 페이코",
      "installment": "일시불",
      "billingAmount": 4500,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 22,
      "origId": 194,
      "date": "2026-09-04",
      "time": "10:13:22",
      "month": "9월",
      "category": "식비",
      "subCategory": "고기",
      "merchant": "춘천그린식품 강명희",
      "amount": 15230,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 15230,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 23,
      "origId": 195,
      "date": "2026-09-04",
      "time": "10:33:15",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "토스쇼핑",
      "amount": 5700,
      "origPay": "토스 간편결제",
      "actualCard": "[간편결제] 토스",
      "installment": "일시불",
      "billingAmount": 5700,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 24,
      "origId": 196,
      "date": "2026-09-04",
      "time": "11:40:48",
      "month": "9월",
      "category": "식비",
      "subCategory": "한식",
      "merchant": "먹보대장",
      "amount": 5500,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5500,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 25,
      "origId": 197,
      "date": "2026-09-04",
      "time": "15:13:30",
      "month": "9월",
      "category": "금융",
      "subCategory": "보험",
      "merchant": "삼성화재해상보험(주)",
      "amount": 55000,
      "origPay": "MG+ S 하나카드",
      "actualCard": "MG+ S 하나카드",
      "installment": "일시불",
      "billingAmount": 55000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 26,
      "origId": 198,
      "date": "2026-09-04",
      "time": "15:14:37",
      "month": "9월",
      "category": "주거/통신",
      "subCategory": "가스비",
      "merchant": "주식회사 예스코",
      "amount": 10750,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 10750,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 27,
      "origId": 199,
      "date": "2026-09-04",
      "time": "15:39:31",
      "month": "9월",
      "category": "교육/학습",
      "subCategory": "학원/강의",
      "merchant": "파이어랩",
      "amount": 19000,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 19000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 28,
      "origId": 200,
      "date": "2026-09-04",
      "time": "19:15:28",
      "month": "9월",
      "category": "뷰티/미용",
      "subCategory": "피부과",
      "merchant": "유앤아이의원",
      "amount": 107500,
      "origPay": "MG+ S 하나카드",
      "actualCard": "MG+ S 하나카드",
      "installment": "일시불",
      "billingAmount": 107500,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 29,
      "origId": 201,
      "date": "2026-09-05",
      "time": "02:55:24",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "서비스구독",
      "merchant": "Apple Services",
      "amount": 2500,
      "origPay": "네이버페이 간편결제(포인트)",
      "actualCard": "[간편결제] 네이버페이(포인트)",
      "installment": "일시불",
      "billingAmount": 2500,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 30,
      "origId": 203,
      "date": "2026-09-05",
      "time": "14:05:59",
      "month": "9월",
      "category": "문화/여가",
      "subCategory": "게임",
      "merchant": "나인원 보드게임카페24",
      "amount": 24000,
      "origPay": "KT Plus 우리카드",
      "actualCard": "KT Plus 우리카드",
      "installment": "일시불",
      "billingAmount": 24000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 31,
      "origId": 205,
      "date": "2026-09-06",
      "time": "10:41:41",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "주식회사 카카오",
      "amount": 45900,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 45900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 32,
      "origId": 206,
      "date": "2026-09-06",
      "time": "14:41:29",
      "month": "9월",
      "category": "카페/간식",
      "subCategory": "커피/음료",
      "merchant": "투썸플레이스_4",
      "amount": 5800,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5800,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 33,
      "origId": 207,
      "date": "2026-09-06",
      "time": "17:37:55",
      "month": "9월",
      "category": "금융",
      "subCategory": "은행",
      "merchant": "송금 내역",
      "amount": 4000,
      "origPay": "카카오페이 머니",
      "actualCard": "계좌/현금",
      "installment": "일시불",
      "billingAmount": 4000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 34,
      "origId": 208,
      "date": "2026-09-06",
      "time": "18:51:23",
      "month": "9월",
      "category": "여행/숙박",
      "subCategory": "여행",
      "merchant": "하나카드 주식회사",
      "amount": 138000,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 138000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 35,
      "origId": 209,
      "date": "2026-09-07",
      "time": "00:00:00",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "aliexpress",
      "amount": -2198,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": -2198,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 36,
      "origId": 211,
      "date": "2026-09-07",
      "time": "11:32:41",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "서비스구독",
      "merchant": "네이버플러스멤버십",
      "amount": 4900,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 4900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 37,
      "origId": 212,
      "date": "2026-09-07",
      "time": "13:35:01",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 24290,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 24290,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 38,
      "origId": 213,
      "date": "2026-09-07",
      "time": "14:53:54",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡",
      "amount": 5999,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5999,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 39,
      "origId": 214,
      "date": "2026-09-07",
      "time": "15:50:59",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 13290,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 13290,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 40,
      "origId": 215,
      "date": "2026-09-07",
      "time": "18:49:51",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "하나카드 주식회사",
      "amount": 45500,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 45500,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 41,
      "origId": 217,
      "date": "2026-09-08",
      "time": "11:37:49",
      "month": "9월",
      "category": "카페/간식",
      "subCategory": "커피/음료",
      "merchant": "(주) 카페크리스피",
      "amount": 5800,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5800,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 42,
      "origId": 218,
      "date": "2026-09-08",
      "time": "11:38:09",
      "month": "9월",
      "category": "카페/간식",
      "subCategory": "커피/음료",
      "merchant": "(주) 카페크리스피",
      "amount": 5800,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 5800,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 43,
      "origId": 219,
      "date": "2026-09-08",
      "time": "17:08:03",
      "month": "9월",
      "category": "식비",
      "subCategory": "배달",
      "merchant": "요기요",
      "amount": 11000,
      "origPay": "페이코 간편결제",
      "actualCard": "[간편결제] 페이코",
      "installment": "일시불",
      "billingAmount": 11000,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 44,
      "origId": 220,
      "date": "2026-09-08",
      "time": "17:08:03",
      "month": "9월",
      "category": "식비",
      "subCategory": "배달",
      "merchant": "요기요",
      "amount": 3200,
      "origPay": "페이코 간편결제",
      "actualCard": "[간편결제] 페이코",
      "installment": "일시불",
      "billingAmount": 3200,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 45,
      "origId": 222,
      "date": "2026-09-09",
      "time": "11:45:00",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "재단법인 한국우편사업진흥원",
      "amount": 15960,
      "origPay": "카카오페이 간편결제",
      "actualCard": "[간편결제] 카카오페이",
      "installment": "일시불",
      "billingAmount": 15960,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 46,
      "origId": 223,
      "date": "2026-09-09",
      "time": "12:20:39",
      "month": "9월",
      "category": "의료/건강",
      "subCategory": "치과",
      "merchant": "서울우리원치과의",
      "amount": 75700,
      "origPay": "KT Plus 우리카드",
      "actualCard": "KT Plus 우리카드",
      "installment": "일시불",
      "billingAmount": 75700,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 47,
      "origId": 224,
      "date": "2026-09-10",
      "time": "00:00:00",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "ALIEXPRESS",
      "amount": -8070,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": -8070,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 48,
      "origId": 226,
      "date": "2026-09-10",
      "time": "11:14:04",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "쿠팡(주)",
      "amount": 8990,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 8990,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 49,
      "origId": 227,
      "date": "2026-09-10",
      "time": "11:37:30",
      "month": "9월",
      "category": "식비",
      "subCategory": "중식",
      "merchant": "샹츠마라 종로점",
      "amount": 10950,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 10950,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 50,
      "origId": 228,
      "date": "2026-09-10",
      "time": "12:30:07",
      "month": "9월",
      "category": "패션/쇼핑",
      "subCategory": "패션",
      "merchant": "모노로그명동",
      "amount": 16900,
      "origPay": "신한은행 The More",
      "actualCard": "신한은행 The More",
      "installment": "일시불",
      "billingAmount": 16900,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 51,
      "origId": 229,
      "date": "2026-09-10",
      "time": "16:59:53",
      "month": "9월",
      "category": "교통",
      "subCategory": "대중교통",
      "merchant": "티머니GO",
      "amount": 51800,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 51800,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 52,
      "origId": 230,
      "date": "2026-09-10",
      "time": "17:33:09",
      "month": "9월",
      "category": "교통",
      "subCategory": "대중교통",
      "merchant": "티머니GO",
      "amount": 53400,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 53400,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 53,
      "origId": 231,
      "date": "2026-09-10",
      "time": "17:40:18",
      "month": "9월",
      "category": "교통",
      "subCategory": "대중교통",
      "merchant": "티머니GO",
      "amount": 53400,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": 53400,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 54,
      "origId": 232,
      "date": "2026-09-10",
      "time": "17:41:32",
      "month": "9월",
      "category": "교통",
      "subCategory": "대중교통",
      "merchant": "티머니GO",
      "amount": -53400,
      "origPay": "네이버페이 간편결제",
      "actualCard": "[간편결제] 네이버페이",
      "installment": "일시불",
      "billingAmount": -53400,
      "exclude": "N",
      "memo": ""
    },
    {
      "id": 55,
      "origId": 233,
      "date": "2026-09-10",
      "time": "23:40:06",
      "month": "9월",
      "category": "온라인쇼핑",
      "subCategory": "인터넷쇼핑",
      "merchant": "토스쇼핑",
      "amount": 8999,
      "origPay": "토스 간편결제",
      "actualCard": "[간편결제] 토스",
      "installment": "일시불",
      "billingAmount": 8999,
      "exclude": "N",
      "memo": ""
    }
  ]
};
